[package]
name = "webtron"
description = "A networked-multiplayer clone of the classic 'Tron Lightcycles' arcade game!"
version = "2.0.0"
authors = ["alecdwm <alec@owls.io>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-files = "0.1.4"
actix-server = "0.6.1"
actix-web = "1.0.8"
actix-web-actors = "1.0.2"
chrono = { version = "0.4.9", features = ["serde"] }
debug_stub_derive = "0.3.0"
failure = "0.1.5"
log = "0.4.8"
nalgebra = { version = "0.18.1", features = ["serde-serialize"] }
pretty_env_logger = "0.3.1"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
structopt = "0.3.2"
uuid = { version = "0.7.4", features = ["v4", "serde"] }
