[package]
name = "webtron"
description = "A networked-multiplayer clone of the classic 'Tron Lightcycles' arcade game!"
version = "2.0.0"
authors = ["alecdwm <alec@owls.io>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
futures = "0.1.26"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
structopt = "0.2.14"
uuid = { version = "0.7.4", features = ["v4"] }
warp = "0.1.15"
